#!/usr/bin/env node
var http = require('http');
var spawn = require('child_process');
var info = require('./config.json');
var key = info.key;
var steamid = info.steamid
var getGames = require('./getGames');
function searchGames(rawname, games, callback){
	games.response.games.forEach(function(game){
				var name = '';
				const dirname = spawn.exec('bash ./getid '+game.appid, function(err, out, stderr){
					out = out.replace('"', "");
					out = out.trim();
					if(out == rawname){
						callback(game.appid, game, out)
					}
				});
	})
}
getGames(steamid, key,  1, function(games){
	var dirname = '';
	args = process.argv;
	args.splice(0, 2)
	args.forEach(function(arg, index){
		dirname += arg;
		if(index+1 !== args.length){
			dirname += " "
		}
	})
	searchGames(dirname, games, function(id, game, out){
		console.log(game.name.toLowerCase().replace(/: /g, "_").replace("-", "_").replace(/ /g, "_").replace(",", "").replace("™", ""))
		console.log('steam://rungameid/'+id);
	})
});
