#!/bin/bash

IFS='
'
array=( `ls  --format=single-column ~/.local/share/Steam/steamapps/common | tr -d /` )
cd ~/steam_suite
for element in "${array[@]}"
do
    bash ./createsteamshortcut $element $1
done
